spring:
  kafka:
    bootstrap-servers: localhost:29092
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:promotiondb
    username: 'admin'
    password: 'admin'

server:
  port: 8083

